### PR TITLE
404page added

### PR DESCRIPTION
**Pull request by FrozenGirl-spd**
The first PR . Suggestions please:)

### CODE REVIEW

**Comment by praveenscience** [comment]
First check: https://deploy-preview-76--footsteps-app.netlify.com/dlskjfsdlkfj
Doesn't work. Let me review the changes.

**Comment by praveenscience** [comment]
Can you please check how to work with Gatsby and push the code again, please? 😊

**Comment by xlogix** [comment]
Maybe we can keep the PR open? Let them fix the issue themselves?

**Comment by xlogix** [comment]
@praveenscience Can you take a session on Gatsby for everyone in the channel?

**Comment by xlogix** [comment]
This issue has been resolved. Thank you for your contribution!

**Pull request closed without merging**
