### PR TITLE
Added image in About Footsteps section

### PR DESCRIPTION
**Pull request by ramneek008**
Resolved issue #154

### CODE REVIEW

**Comment by xlogix** [comment]
Can we change the image to something else?

**Comment by ramneek008** [comment]
Yes, will you provide the image or shall I find it on my own?

**Comment by xlogix** [comment]
You can search a good one :)

**Comment by ramneek008** [comment]
You can check now.

**Comment by xlogix** [comment]
@ramneek008 Although the image is good, it's not showing up properly on the page. It's width is too low

**Comment by ramneek008** [comment]
Width resolved responsively.

**Comment by xlogix** [comment]
Merged!

**Pull request merged**
