### PR TITLE
Added the url validator function

### PR DESCRIPTION
**Pull request by imrishabh18**

### CODE REVIEW

**Comment by xlogix** [comment]
Hey nice work! I'm pretty sure we don't need ftp or smtp match here. So, maybe ask the user for only http links. And, include these checks in the profile page too (as these fields are optional).

Also, why don't you add a regex for other text fields in the sign up flow? You can raise another issue for this and send another PR.

**Comment by R3l3ntl3ss** [comment]
Looks good. Merging.

**Comment by xlogix** [comment]
@imrishabh18 Use this regex instead! https://www.regextester.com/94502

@praveenscience found a bug!

**Comment by imrishabh18** [comment]
Okay will use that regex

**Comment by xlogix** [comment]
@imrishabh18 Waiting for the PR

**Comment by imrishabh18** [comment]
@xlogix when changing the regex and commting it is giving this error eslint error

**Comment by xlogix** [comment]
What's the error? Can you put the screenshot here

**Comment by imrishabh18** [comment]
image

Check the right side. And also when i was running this regex in my local machine it was running perfect but shows linting error when pushed.

**Pull request merged**
