### PR TITLE
Modified the landing page (#48)

### PR DESCRIPTION
**Pull request by annu12340**
one
two
three
four

### CODE REVIEW

**Comment by xlogix** [comment]
Very good initiative @annu12340! Although, I would appreciate if you can move this content to the login page for now. This is because people arrive at the login page first and we can't change the flow at this moment.

**Comment by annu12340** [comment]
> Very good initiative @annu12340! Although, I would appreciate if you can move this content to the login page for now. This is because people arrive at the login page first and we can't change the flow at this moment.

Thank you :)
But isn't this the content that should be there on the landing page? Also, I couldn't get what you meant you by 'move this content to the login page for now.' Could you repeat it once again and tell me what all changes I should make?

**Comment by xlogix** [comment]
> Thank you :)
> But isn't this the content that should be there on the landing page? Also, I couldn't get what you meant you by 'move this content to the login page for now.' Could you repeat it once again and tell me what all changes I should make?

This is the right content for the landing page but when you visit footsteps.dev from the browser, the first page is the login page. That is the page to which you should add this content to.

**Comment by annu12340** [comment]
> > Thank you :)
> > But isn't this the content that should be there on the landing page? Also, I couldn't get what you meant you by 'move this content to the login page for now.' Could you repeat it once again and tell me what all changes I should make?
> 
> This is the right content for the landing page but when you visit footsteps.dev from the browser, the first page is the login page. That is the page to which you should add this content to.

So all I need to do is to copy-paste this content to Login/loginFlow component, right?

**Comment by xlogix** [comment]
Yup, let's start there. Dakshan and I will be reviewing the code once you move the code to the login component.

**Comment by annu12340** [comment]
Can I change this image in the login page to something else image

**Comment by xlogix** [comment]
> Can I change this image in the login page to something else image

Yup, go ahead. Whatever you think would look good.

**Pull request closed without merging**
