### PR TITLE
Public profile url

### LINKED ISSUE #106: Show user's image & Name in public profile link
The public profile URL doesn't have proper meta tags which show an image of the user & name while sharing on social media.

Try sharing your public profile page on WhatsApp or Telegram to test the link

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #106 
image

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@xlogix Please check

**Comment by xlogix** [comment]
Hey Shreya, Add an icon/button instead of a link and place it somewhere else maybe?

**Comment by shreyakapoor08** [comment]
> Hey Shreya, Add an icon/button instead of a link and place it somewhere else maybe?

image

Is it fine ?

**Comment by xlogix** [comment]
Place a button or icon with the link at the corner of the About card. You can also try putting it beside the name. Whatever looks good in the end

**Comment by xlogix** [comment]
Thanks!

**Comment by shreyakapoor08** [comment]
@xlogix Kindly add labels to it

**Pull request merged**
