### PR TITLE
Adding regex for text field

### LINKED ISSUE #79: Adding regex for the text fields in the signup page.

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #79

### CODE REVIEW

**Comment by xlogix** [comment]
Is this working perfectly for all fields? Have you checked thoroughly?
Does the URL validator accept this link? https://twitter.com/hello_world

**Comment by pydevsg** [comment]
@shreyakapoor08 please do the necessary said by @xlogix so that we can merge your PR, if you need any help feel free to reach out.

**Comment by xlogix** [comment]
@shreyakapoor08 Any updates? I can merge as soon as you verify

**Comment by shreyakapoor08** [comment]
Hi, sorry. I will confirm you about the same by today evening

**Comment by shreyakapoor08** [comment]
> Is this working perfectly for all fields? Have you checked thoroughly?
> Does the URL validator accept this link? https://twitter.com/hello_world

Yes I have checked it, the URL validator was not working properly..I have corrected that too. You can check now

**Comment by xlogix** [comment]
Great @shreyakapoor08. One more thing, instead of showing an alert, can we instead show an error on the text field itself? Maybe shake the text field?

**Comment by shreyakapoor08** [comment]
Okay I will do that

**Comment by shreyakapoor08** [comment]
@xlogix Kindly check

**Comment by xlogix** [comment]
Merged!

**Comment by shreyakapoor08** [comment]
Kindly consider changing the difficulty label of this PR 😊 @xlogix

**Comment by xlogix** [comment]
Done

**Pull request merged**
