### PR TITLE
Modified the landing page (#48)

### PR DESCRIPTION
**Pull request by annu12340**
Screenshot
two
three
four

### CODE REVIEW

**Comment by xlogix** [comment]
Can you change the primary color to green? We must have seen it being used throughout the app.

**Comment by annu12340** [comment]
> Can you change the primary color to green? We must have seen it being used throughout the app.

From red to green?

**Comment by annu12340** [comment]
I have made the requested change

**Comment by xlogix** [comment]
Please add appropriate content too!

**Comment by R3l3ntl3ss** [comment]
Hey Annu,
This looks really good. I just made some changes to make it more mobile-friendly. 

Is it possible to get a higher resolution version of the image you used on the landing page?  It looks a bit pixelated..  It would be great if we use a higher resolution.

**Comment by annu12340** [comment]
> Hey Annu,
> This looks really good. I just made some changes to make it more mobile-friendly.
> 
> Is it possible to get a higher resolution version of the image you used on the landing page? It looks a bit pixelated.. It would be great if we use a higher resolution.

Thanks

**Comment by annu12340** [comment]
> Please add appropriate content too!

I have added the content also

**Comment by R3l3ntl3ss** [comment]
Looks good! 
@xlogix What do you think about the changes in the search page?

**Comment by annu12340** [comment]
Any other changes required?

**Comment by xlogix** [comment]
Screenshot 2020-04-08 at 1 51 04 AM

@annu12340 Please add these changes to the Login page instead of the Landing page. That's the first page which people will see when the visit the site.

**Comment by xlogix** [comment]
Looks good! Awesome work @annu12340. @R3l3ntl3ss Can you approve the PR.

**Pull request merged**
