### PR TITLE
Refactored the code 

### PR DESCRIPTION
**Pull request by vngarg**
# Description
I had added a helper/Validation.js file with the functions for validation and had also refactored the code in Statefull and Stateless components.
this PR closes the issue #68

### CODE REVIEW

**Comment by xlogix** [comment]
Do pass the checks!!

**Comment by vngarg** [comment]
> Do pass the checks!!

I don't know what these checks means ..
I also dont know what was wrong with the code that these errors occured and how to overcome these checks

**Comment by praveenscience** [comment]
@vngarg You need to read why. As simple as that.

**Comment by vngarg** [comment]
I tried but can't find more errors, I could just resolve one error.
Could you please help ??

**Comment by xlogix** [comment]
I'm closing this PR as you've raised another one. We'll discuss there

**Pull request closed without merging**
