### PR TITLE
Learning path public profile #61

### PR DESCRIPTION
**Pull request by prajwal714**
added the feature of Public Paths visible. Suggest In case of changes .

### CODE REVIEW

**Comment by prajwal714** [comment]
Okay I'll make the changes @R3l3ntl3ss and get back to you.

**Comment by prajwal714** [comment]
Done with the changes. @R3l3ntl3ss . Kindly review and merge if okay. @xlogix @R3l3ntl3ss 
Screenshot from 2020-03-03 16-31-19
Screenshot from 2020-03-03 16-31-19

**Comment by xlogix** [comment]
Hey, good job! Just one thing... Did you add the 'isPrivate' flag check as we discussed on the issue?

**Comment by R3l3ntl3ss** [comment]
We need to first add the ability for the user to make the path private while they are creating the path and make changes to the DB schema.

I guess that would be its own issue.

**Comment by prajwal714** [comment]
I have already been working on the private path issue, i have added a switch to choose oublic or private. But the issue now is that it's unable to add a new field using graphQL. I'll send the screenshot of the issur.

**Comment by xlogix** [comment]
@R3l3ntl3ss Yea we have to do that but right now we can simply keep every path public and have the value in the DB as 'true'.  I mentioned it here so we can finish off the public profile page altogether? What do you think? 
The part where we have to add it to the frontend will be a separate issue on itself.

@prajwal714 Try sending a screenshot? Let's try to help you add the field in the DB.

**Comment by R3l3ntl3ss** [comment]
Hey, so I made changes to the schema. On the app side, we just have to change the query with the condition to get only the public learning path. I have changed that as well in this commit.

**Comment by R3l3ntl3ss** [comment]
@prajwal714 You can work on adding the ability for the user to choose if the path is private while they are creating the path. Also, they have to be able to change that in editPath as well.

**Comment by xlogix** [comment]
Lol alright. That'll all I had in mind. Approving this and pushing.

**Comment by prajwal714** [comment]
The issue was one time only, its now succesfully adding a private path with no errors. And since the query is updated , the search results will show only the public paths. I have added a UI switch to select if the user wants to make it private.
Screenshot from 2020-03-03 19-03-47

**Comment by xlogix** [comment]
Awesome! Although, I'm not sure if that's the best place for keeping that switch.  Maybe add it to the top near 'Create a new path' text

**Pull request merged**
