### PR TITLE
Added User progress bar #63

### PR DESCRIPTION
**Pull request by prajwal714**

### CODE REVIEW

**Comment by prajwal714** [comment]
@xlogix @R3l3ntl3ss Kindly review and merge if the design is final.

**Comment by prajwal714** [comment]
Screenshot from 2020-03-07 20-15-46
Screenshot from 2020-03-07 20-15-32
The current progress Bar looks like this. @xlogix @R3l3ntl3ss

**Comment by xlogix** [comment]
@prajwal714 Can you resolve the conflicts?

**Comment by prajwal714** [comment]
I can't seem to understand why the merge conflict is occurring, in both the branches changes seem to be the same. It's not showing a merge conflict in my VS Code, 
I did fetch and merge the master branch from upstream too. 
@xlogix I would need your help on this. Maybe I am doing something wrong.

**Comment by xlogix** [comment]
Closing this pull request.

**Pull request closed without merging**
