### PR TITLE
Migrate react-tags-input

### PR DESCRIPTION
**Pull request by imrishabh18**

### CODE REVIEW

**Comment by imrishabh18** [comment]
@xlogix  Hey, why did the commits of other branch is shown here ?

**Comment by xlogix** [comment]
@imrishabh18 Are you branching from the master branch or did you do it from some other branch?

Make sure you are on Master, then do fetch upstream & then merge upstream/master. After that, do npm install & then you can add your changes to a new branch.

Meanwhile, keep your fork clean by deleting unnecessary branches.

**Comment by imrishabh18** [comment]
@xlogix Okay. Any changes required in this thing ?

**Comment by xlogix** [comment]
@imrishabh18 Send a new PR

**Pull request closed without merging**
