### PR TITLE
migrating 'react-tag-input' dependency to 'react-tag-autocomplete'

### LINKED ISSUE #86: Migrate 'react-tag-input' dependency to 'react-tag-autocomplete' & add basic autocomplete suggestions
React Tag Input dependency is used in the on-boarding process of the app when the user enters his/her skills. This process can take a while since there are no auto-complete suggestions in the tags. We should add basic complete options for skills.

Link to the package: https://www.npmjs.com/package/react-tag-autocomplete

Make sure to remove peer dependencies of react-tag-input as well.

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #86

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@xlogix is it correct?

**Comment by shreyakapoor08** [comment]
> Hey Shreya,
> I am getting this error in the addPath and editPath components.
> 
> Screenshot from 2020-04-19 17-43-01
> 
> Could you please fix it and update here.

Kindly check now

**Comment by xlogix** [comment]
How do we dynamically add new suggestions to the array as the users add their skills?

**Comment by shreyakapoor08** [comment]
> Hey Shreya,
> I am facing the same issue on the sign-up page too. Could you fix it there as well?
> Also, could you run `npm run format` before you commit? I see that your formatter has changed a lot of lines unnecessarily.

Please check now

**Pull request merged**
