### PR TITLE
Mark as done icon added

### PR DESCRIPTION
**Pull request by aditianshu**

### CODE REVIEW

**Comment by xlogix** [comment]
Need some help over here?

**Comment by aditianshu** [comment]
The code review was failing. The blocks {} used while importing Rows, Columns and other components from Ant were declared not useful but it can't be done without the parenthesis, importing them individually didn't work either.
How should I go about it?

**Comment by xlogix** [comment]
@aditianshu This is fine. We can merge it. Please push the changes here. #52

**Comment by xlogix** [comment]
Can you remove the two cache folders that have been added? they start with reduxcache...

**Comment by xlogix** [comment]
thanks!

**Comment by aditianshu** [comment]
Thank you! :)

**Pull request merged**
